// Generated by CoffeeScript 1.7.1
var c, ctx, d, draw;

// c = new fabriapp.v.app.vWithViewport("zoomable_app.v", {
//   isDrawingMode: true
// });

// app.v.isDrawingMode = false;

// d = $("#zoomable_app.v");

// ctx = d[0].getContext("2d");

// draw = function() {
//   return ctx.fillStyle = "#000";
// };

$("#width-obj").val(app.b.width);
$("#height-obj").val(app.b.height);

$(".buttons .edit").click(function() {
  $(this).addClass("active");
  $(".buttons a").not(this).removeClass("active");
  app.v.isDrawingMode = false;
  app.v.isGrabMode = false;
  return false;
});

$(".buttons .pencil").click(function() {
  $(this).addClass("active");
  $(".buttons a").not(this).removeClass("active");
  app.v.isDrawingMode = true;
  app.v.isGrabMode = false;
  return false;
});

$(".buttons .grab").click(function() {
  $(this).addClass("active");
  $(".buttons a").not(this).removeClass("active");
  app.v.isDrawingMode = false;
  app.v.isGrabMode = true;
  return false;
});

$(".buttons .zoom-in").click(function() {
  app.v.setZoom(app.v.viewport.zoom * 1.1);
  return false;
});

$(".buttons .zoom-out").click(function() {
  app.v.setZoom(app.v.viewport.zoom / 1.1);
  return false;
});

$(".buttons .eraser").click(function() {
  app.v.clear();
  return false;
});

$(".buttons .apply").click(function() {
  var height, width;
  width = parseInt($("#width-obj").val());
  height = parseInt($("#height-obj").val());
  app.b.setHeight(height);
  app.b.setWidth(width);
  return app.v.renderAll();
});

$("#height-obj").on("input", function(e) {
  var height, width;
  width = parseInt($("#width-obj").val());
  height = parseInt($("#height-obj").val());
  app.b.setHeight(height);
  app.b.setWidth(width);
  return app.v.renderAll();
});

$("#width-obj").on("input", function(e) {
  var height, width;
  width = parseInt($("#width-obj").val());
  height = parseInt($("#height-obj").val());
  app.b.setHeight(height);
  app.b.setWidth(width);
  return app.v.renderAll();
});

$("#menu-close").click(function(e) {
  e.preventDefault();
  return $("#sidebar-wrapper").toggleClass("active");
});

$("#menu-toggle").click(function(e) {
  e.preventDefault();
  return $("#sidebar-wrapper").toggleClass("active");
});

app.v.on('after:render', function() {
  return this.calcOffset();
});

globscale=1;

function displaywheel(e){
    var SCALE_FACTOR = 1.1;
  var evt=window.event || e
  var delta=evt.detail? evt.detail*(-120) : evt.wheelDelta
  var objects = app.v.getObjects();
  var dd = 1;
  if (delta == 120) dd=SCALE_FACTOR;
  if (delta == -120) dd=1/SCALE_FACTOR;
  globscale = globscale * dd;
    for (var i in objects) {
    objects[i].scaleX = globscale;
    objects[i].scaleY = globscale;
    objects[i].left = objects[i].left * dd;
    objects[i].top = objects[i].top * dd;
    objects[i].setCoords();
  }
  app.v.renderAll();
    app.v.calcOffset();
}
var mousewheelevt=(/Firefox/i.test(navigator.userAgent))? "DOMMouseScroll" : "mousewheel"
if (document.attachEvent) document.attachEvent("on"+mousewheelevt, displaywheel) 
else if (document.addEventListener) document.addEventListener(mousewheelevt, displaywheel, false)